name: Jumping Chihuahua Productions
favicon: null
layout_spectrum: 0.9515995848923922
typography_spectrum: 0.588790554087609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9625023829285055
  lightness: 0.8151323187630624
  saturation: 0.038562373258173466
  rhythmicContrast: 0.8151554332580417
purpose: []
